import type { HomeData, SiteCard } from "./home-data";
import styles from "./website.module.css";

function CardImage({ item }: { item: SiteCard }) {
  return <div className={styles.cardImage}>{item.image ? <img src={item.image.url} alt={item.image_alt || item.name} width={item.image.width} height={item.image.height} loading="lazy" /> : <span aria-label="Chưa có ảnh">{item.name.charAt(0)}</span>}{item.is_new && <small>Mới</small>}</div>;
}

export default function HomeSections({ data }: { data: HomeData }) {
  const price = (value: string) => new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(Number(value));
  return <><section id="products" className={styles.section}><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>KHÁM PHÁ BỘ SƯU TẬP</span><h2>Sản phẩm của chúng tôi</h2></div><a className={styles.textLink} href="#contact">Tư vấn lựa chọn <span aria-hidden="true">↗</span></a></div>{data.products.length ? <div className={styles.productGrid}>{data.products.map(item => <article className={styles.productCard} key={item.id}><CardImage item={item} /><h3>{item.name}</h3>{item.description && <p>{item.description}</p>}<div className={styles.price}>{item.sale_price && Number(item.sale_price) > 0 && Number(item.sale_price) < Number(item.regular_price) ? <><strong>{price(item.sale_price)}</strong><del>{price(item.regular_price || "0")}</del></> : <strong>{Number(item.regular_price) > 0 ? price(item.regular_price!) : "Liên hệ tư vấn"}</strong>}</div><a href="#contact" className={styles.textLink}>Tìm hiểu thêm ↗</a></article>)}</div> : <div className={styles.empty}><span>ĐANG CẬP NHẬT</span><h3>Bộ sưu tập mới sắp được giới thiệu.</h3><p>Liên hệ với chúng tôi để được tư vấn sản phẩm phù hợp.</p><a href="#contact" className={styles.textLink}>Liên hệ ngay →</a></div>}</section>
    {data.about && <section id="about" className={styles.about}><div className={styles.aboutImage}>{data.about.image ? <img src={data.about.image.url} alt={data.about.image_alt || data.about.name} width={data.about.image.width} height={data.about.image.height} loading="lazy" /> : <div className={styles.aboutPlaceholder}>{data.company.name || "Câu chuyện của chúng tôi"}</div>}</div><div className={styles.aboutCopy}><span className={styles.eyebrow}>VỀ CHÚNG TÔI</span><h2>{data.about.name}</h2>{data.about.description && <p>{data.about.description}</p>}{data.about.content && <details className={styles.aboutDetails}><summary>Đọc câu chuyện của chúng tôi</summary><div className={styles.richText} dangerouslySetInnerHTML={{ __html: data.about.content }} /></details>}<a className={styles.primaryButton} href="#contact">Kết nối cùng chúng tôi ↗</a></div></section>}
    <section id="news" className={styles.section}><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>CÂU CHUYỆN & CẢM HỨNG</span><h2>Tin tức mới nhất</h2></div><span className={styles.muted}>Những cập nhật từ {data.company.name || "chúng tôi"}</span></div>{data.news.length ? <div className={styles.newsGrid}>{data.news.map(item => <article key={item.id} className={styles.newsCard}><CardImage item={item} /><span className={styles.eyebrow}>TIN TỨC</span><h3>{item.name}</h3><p>{item.description || "Nội dung đang được cập nhật."}</p></article>)}</div> : <p className={styles.emptyNews}>Những câu chuyện mới đang được chuẩn bị. Hẹn gặp bạn sớm!</p>}</section>
  </>;
}
