import type { HomeData } from "./home-data";
import { safeLink } from "./site-links";
import styles from "./website.module.css";

export default function SiteFooter({ data }: { data: HomeData }) {
  const name = data.company.name || "Website";
  const logo = data.media["logo-footer"]?.[0] || data.media.logo?.[0];
  const phone = data.company.hotline || data.company.phone;
  const socials = data.media["social-footer"] || data.media.social || [];
  return <footer id="contact" className={styles.footer}><div className={styles.footerCallout}><div><span className={styles.eyebrow}>CHÚNG TÔI LUÔN SẴN SÀNG LẮNG NGHE</span><h2>Cùng bắt đầu một cuộc trò chuyện.</h2></div>{phone ? <a href={`tel:${phone.replace(/[^+\d]/g, "")}`} className={styles.lightButton}>{phone} ↗</a> : data.company.email && <a className={styles.lightButton} href={`mailto:${data.company.email}`}>Gửi email ↗</a>}</div><div className={styles.footerGrid}><div>{logo ? <img className={styles.footerLogo} src={logo.image.url} alt={logo.alt || name} width={logo.image.width} height={logo.image.height} loading="lazy" /> : <h3>{name}</h3>}<p>{data.company.slogan || "Cảm ơn bạn đã ghé thăm website của chúng tôi."}</p><div className={styles.socials}>{socials.map(item => safeLink(item.link) && <a key={item.id} href={safeLink(item.link)} aria-label={item.name || item.alt || "Mạng xã hội"}><img src={item.image.url} alt={item.alt || item.name} width={26} height={26} loading="lazy" /></a>)}</div></div><div><h3>Khám phá</h3><a href="#home">Trang chủ</a>{data.about && <a href="#about">Giới thiệu</a>}<a href="#products">Sản phẩm</a><a href="#news">Tin tức</a></div><div><h3>Thông tin liên hệ</h3>{data.company.address && <p>{data.company.address}</p>}{phone && <a href={`tel:${phone.replace(/[^+\d]/g, "")}`}>{phone}</a>}{data.company.email && <a href={`mailto:${data.company.email}`}>{data.company.email}</a>}{data.company.worktime && <p>{data.company.worktime}</p>}</div></div><div className={styles.footerBottom}><span>{data.company.copyright || `© ${new Date().getFullYear()} ${name}. All rights reserved.`}</span><div>{[...(data.media.dmca || []), ...(data.media.bct || [])].map(item => <a key={item.id} href={safeLink(item.link)}><img src={item.image.url} alt={item.alt || item.name || "Chứng nhận"} width={100} height={25} loading="lazy" /></a>)}</div><a href="#home">Về đầu trang ↑</a></div></footer>;
}
