<?php 
@define ('_albumanh','Album ảnh');
@define ('_lienketmxh','Liên kết MXH');
@define ('_giolamviec','Giờ làm việc');
@define ('_tieudelienhe','Vui lòng điền thông tin để nhận thông tin khuyến mại từ chúng tôi');
@define ('_chiduong','Chỉ đường');
@define ('_goidien','Gọi điện');
@define ('_ketqua','Kết quả');
@define ('_timthay','Tìm thấy');
@define ('_timkiem','Tìm kiếm');
@define ('_dongsanpham','Dòng sản phẩm');
@define ('_nganhcongnghiep','Ngành công nghiệp và ngành');
@define ('_chinhsachquydinh','Chính sách & Quy định');
@define ('_theloai','Thể loại');
@define ('_dangkykhongthanhcong','Đăng ký không thành công . Vui lòng thử lại ');
@define ('_emaildaduocdangky','Email đã được đăng ký !');
@define ('_dangkythanhcong','Đăng ký thành công !');
@define ('_emailkhonghople','Email không hợp lệ');
@define ('_banchuanhapemail','Bạn chưa nhập email');
@define ('_banchuanhaptukhoa','Bạn chưa nhập từ khóa');
@define ('_lamlai','Làm lại');
@define ('_gui','Gửi');
@define ('_noidung','Nội dung');
@define ('_tieude','Tiêu đề');
@define ('_diachi','Địa chỉ');
@define ('_dienthoai','Điện thoại');
@define ('_sodienthoai','Số điện thoại');
@define ('_hovaten','Họ và tên');
@define ('_baivietkhac','Bài viết khác');
@define ('_xemchitiet','Xem chi tiết');
@define ('_noidungchuacapnhat','Nội dung chưa cập nhật. Xin vui lòng xem chuyên mục khác.');
@define ('_chitietsanpham','Chi tiết sản phẩm');
@define ('_giaban','Giá bán');
@define ('_sanphamkhac','Sản phẩm khác');
@define ('_binhluan','Bình luận');
@define ('_noidungchitiet','Nội dung chi tiết');
@define ('_gia','Giá');
@define ('_mota','Mô tả');
@define ('_masp','Mã sản phẩm');
@define ('_tongtruycap','Tổng truy cập');
@define ('_thang','Tháng');
@define ('_homnay','Hôm nay');
@define ('_tuannay','Tuần này');
@define ('_ngay','Ngày');
@define ('_dangxem','Đang xem');
@define ('_dangonline','Đang online');
@define ('_online','Online');
@define ('_dangky','Đăng ký');
@define ('_nhapemailcuaban','Nhập email của bạn');
@define ('_ketnoivoichungtoi','Kết nối với chúng tôi');
@define ('_thongketruycap','Thống kê truy cập');
@define ('_vuilongdiendaydu','Vui lòng điền đẩy đủ thông tin và gửi về cho chúng tôi. Chúng tôi sẽ phản hồi sớm nhất.');
@define ('_moithongtindeubaomat','Mọi thông tin đều bảo mật');
@define ('_guingay','Gửi ngay');
@define ('_dangkynhantin','Đăng ký nhận tin');
@define ('_thongtinlienhe','Thông tin liên hệ');
@define ('_videoclip','Video - Clip');
@define ('_tintucsukien','Tin tức - Sự kiện');
@define ('_sanphamnoibat','Sản phẩm nổi bật');
@define ('_dichvuchinh','Dịch vụ chính');
@define ('_danhmucsanpham','Danh mục sản phẩm');
@define ('_xemthem','Xem thêm');
@define ('_hotlinetuvan','Hotline tư vấn');
@define ('_thongtinlienheduocgui','Thông tin liên hệ đã được gửi thành công');
@define ('_hethongloi','Hệ thống lỗi. Vui lòng thử lại!');
@define ('_lienhe','Liên hệ');
@define ('_tuyendung','Tuyển dụng');
@define ('_tintuc','Tin tức');
@define ('_dichvu','Dịch vụ');
@define ('_sanpham','Sản phẩm');
@define ('_gioithieu','Giới thiệu');
@define ('_trangchu','Trang chủ');
@define ('_chatluong','Chất lượng');
@define ('_thitruong','Thị trường');
@define ('_dautu','Đầu tư');
@define ('_thongtin','Thông tin');
@define ('_giohang','Giỏ hàng');
@define ('_thanhtoan','Thanh toán');
@define ('_clickvaodayneukhongmuondoilau','Click vào đây nếu không muốn đợi lâu');
@define ('_thongbao','Thông báo');
@define ('_email','Email');
@define ('_maxacnhankhongchinhxac','Mã xác nhận không chính xác');
@define ('_themvaogiohang','Thêm và giỏ hàng');
@define ('_chuacosanpham','Chưa có sản phẩm');
@define ('_luotxem','Lượt xem');
@define ('_sanphamduocthem','Sản phẩm này đã được thêm vào giỏ hàng của bạn');
@define ('_tieptucmuahang','Tiếp tục mua hàng');
@define ('_xemgiohang','Xem giỏ hàng');
@define ('_hinhanh','Hình ảnh');
@define ('_ten','Tên');
@define ('_soluong','Số lượng');
@define ('_tong','Tổng');
@define ('_thaotac','Thao tác');
@define ('_muatiep','Mua tiếp');
@define ('_tonggia','Tổng giá');
@define ('_xoatatca','Xóa tất cả');
@define ('_banmuonxoattatcagiohangkhong','Bạn muốn xóa tất cả giỏ hàng');
@define ('_xoasanphamnay','Xóa sản phẩm này');
@define ('_khongcosanphamnaotronggiohang','Không có sản phẩm nào trong giỏ hàng');
@define ('_chungtoinhanraspam','Chúng tôi nhận ra rằng bạn đang spam !!');
@define ('_chinhsach','Chính sách');
@define ('_dathangthanhcong','Đặt hàng thành công');
@define ('_xinloiquykhach','Xin lỗi quý khách.<br>Hệ thống bị lỗi, xin quý khách thử lại');
@define ('_thuvien','Thư viện');
@define ('_taikhoan','Tài khoản');
@define ('_dangxuat','Đăng xuất');
@define ('_sanphamdachon','Sản phẩm đã chọn');
@define ('_muangay','Mua ngay');
@define ('_mangxahoi','Mạng xã hội');
@define ('_chinhsachhotro','Chính sách hỗ trợ');
@define ('_thongtintaikhoan','Thông tin tài khoản');
@define ('_nhapemail','Nhập Email');
@define ('_tukhoatimkiem','Từ khóa tìm kiếm');
@define ('_sanphambanchay','Sản phẩm bán chạy');
@define ('_sanphammoi','Sản phẩm mới');
@define ('_dangnhap','Đăng nhập');
@define ('_tendangnhap','Tên đăng nhập');
@define ('_matkhau','Mật khẩu');
@define ('_dangnhap','Đăng nhập');
@define ('_nhomatkhau','Nhớ mật khẩu');
@define ('_quenmatkhau','Quên mật khẩu');
@define ('_dangkytaikhoan','Đăng ký tài khoản');
@define ('_nhappassword','Nhập mật khẩu (Mật khẩu ít nhất 6 ký tự)');
@define ('_nhappasswordcu','Nhập mật khẩu cũ');
@define ('_nhappasswordmoi','Nhập mật khẩu mới (Mật khẩu ít nhất 6 ký tự)');
@define ('_nhaplaimatkhau','Nhập lại mật khẩu');
@define ('_nhaplaipasswordtren','Nhập lại mật khẩu trên');
@define ('_nhaphoten','Nhập họ tên');
@define ('_nhapdiachi','Nhập địa chỉ');
@define ('_nhapsodienthoai','Nhập số điện thoại');
@define ('_nhaplai','Nhập lại');
@define ('_matkhauitnhat','Mật khẩu ít nhất phải 6 ký tự');
@define ('_matkhaukhongtrungkhop','Mật khẩu không trùng khớp');
@define ('_xinhaynhapemail','Xin hãy nhập email');
@define ('_xinhaynhappassword','Xin hãy nhập mật khẩu');
@define ('_nhaplaimatkhaukhongchinhxac','Nhập lại mật khẩu không chính xác');
@define ('_xinhaynhaphoten','Xin hãy nhập họ tên');
@define ('_xinhaynhapdiachi','Xin hãy nhập địa chỉ');
@define ('_sodienthoaikhongdung','Số điện thoại không đúng');
@define ('_thongtintaikhoan','Số điện thoại không đúng');
@define ('_kichhoattaikhoan','Kích hoạt tài khoản');
@define ('_kichhoattaikhoanthanhcong','Kích hoạt tài khoản thành công');
@define ('_clickvao','Click vào');
@define ('_day','đây');
@define ('_detrovetrangchu','để trở về trang chủ');
@define ('_lichsumuahang','Lịch sử mua hàng');
@define ('_banchuamuasanphamnaotrenwebsite','Bạn chưa mua sản phẩm nào trên website');
@define ('_donhangngay','Đơn hàng ngày');
@define ('_madonhang','Mã đơn hàng');
@define ('_trangthai','Trạng thái');
@define ('_banquenmatkhau','Bạn Quên Mật Khẩu');
@define ('_banhaynhapemailmabandadangky','Bạn hãy nhập Email mà bạn đã đăng ký thành viên vào đây để nhận  Password thông qua mail của bạn');
@define ('_laymatkhauthanhcong','Lấy mật khẩu thành công . Thông tin đăng nhập của bạn là !');
@define ('_laymatkhaukhongthanhcong','Lấy password không thành công . vui lòng lấy lại password !');
@define ('_thongtingiaohang','Thông tin giao hàng');
@define ('_hinhthucthanhtoan','Hình thức thanh toán');
@define ('_ghichu','Ghi chú');
@define ('_banhaydangnhapdecothevaoday','Bạn hãy đăng nhập để có thể vào đây');
@define ('_hangmoive','Hàng mới về');
@define ('_banchay','Bán chạy');
@define ('_uudaihangtuan','Ưu đãi hàng tuần');
@define ('_hoidap','Hỏi đáp');
@define ('_nhapdiachiemailcuaban', 'Nhập địa chỉ email của bạn');
@define ('_quocgia', 'Quốc gia');
@define ('_chonquocgia', 'Chọn quốc gia');
@define ('_tinhthanh', 'Tỉnh/Thành phố');
@define ('_chontinhthanh', 'Chọn Tỉnh/Thành phố');
@define ('_quanhuyen', 'Quận/Huyện');
@define ('_chonquanhuyen', 'Chọn Quận/Huyện');
@define ('_xinhaychonquocgia', 'Xin hãy chọn quốc gia');
@define ('_clickdexemhinhlonhon', 'Click để xem hình lớn hơn');
@define ('_sanphammuakem', 'Sản phẩm mua kèm');
@define ('_phivanchuyen', 'Phí vận chuyển');
@define ('_tongthanhtoan', 'Tổng thanh toán');
@define ('_thongtinhotro', 'Thông tin hỗ trợ');
@define ('_tencongty', 'Tên công ty');
@define ('_thongtindathangtuwebsite', 'Thông tin đặt hàng từ website');
@define ('_dondathang', 'ĐƠN ĐẶT HÀNG');
@define ('_bosuutap', 'Bộ sưu tập');
@define ('_chao', 'Chào');
@define ('_camonbandadangkythanhvientren', 'Cảm ơn bạn đã đăng ký thành viên trên');
@define ('_dekichhoattaikhoan', 'Để kích hoạt tài khoản thành viên , bạn vui lòng nhấn vào liên kết dưới đây');
@define ('_tentruycap', 'Tên truy cập');
@define ('_luuy', 'Lưu Ý');
@define ('_daylathuhotrotudong', 'Đây là thư hổ trợ tự động , mọi phản hồi về mail này điều không được duyệt');
@define ('_xacnhanmatkhau', 'Xác Nhận Mật Khẩu');
@define ('_thongbaotu', 'Thông báo Từ');
@define ('_aidodadungemailnaydelaymatkhau', 'Ai đó đã dùng email này để lấy lại password thành viên của bạn trên trang');
@define ('_neudunglaban', 'Nếu đúng là bạn muốn lấy lại password xin vui lòng nhấn vào links bên dưới để lấy lại thông tin đăng nhập của bạn');
@define ('_nhanvaoday', 'Nhấn Vào Đây');
@define ('_neubankhongyeucaulaylaipass', 'Nếu bạn không yêu cầu lấy lại pass vui lòng bỏ qua email này của chúng tôi');
@define ('_banquenmatkhaunhapemaildelaylai', 'Bạn Quên Mật Khẩu ? . Bạn hãy nhập Email mà bạn đã đăng ký thành viên vào đây để nhận  Password thông qua mail của bạn');
@define ('_guiemail', 'Gửi Email');
@define ('_laypassthanhcong', 'Lấy password thành công . Thông tin đăng nhập của bạn là !');
@define ('_laypasskhongthanhcong', 'Lấy password không thành công . vui lòng lấy lại password !');
@define ('_dangkythanhvien', 'Đăng ký thành viên');
@define ('_banphaikichhoat','Tài khoản của bạn chưa được kích hoạt. Vui lòng vào email đăng ký để kích hoạt !');
@define ('_dangnhapthanhcong','Đăng nhập thành công');
@define ('_tendangnhaphoacmatkhaukhongchinhxac','Tên đăng nhập hoặc mật khẩu không chính xác');
@define ('_bandadangkythanhcong','Bạn đã đăng ký thành công. Vui lòng vào email đăng ký để kích hoạt tài khoản');
@define ('_matkhaumoi','Mật khẩu mới');
@define ('_nhaplaimatkhaumoi','Nhập lại mật khẩu mới');
@define ('_capnhat','Cập nhật');
@define ('_banchuanhapmatkhaucu','Bạn chưa nhập mật khẩu cũ');
@define ('_matkhauchuachinhxac','Mật khẩu chưa chính xác');
@define ('_capnhatthongtinthanhcong','Cập nhật thông tin thành công');
?>