<?php
@define ("_albumanh", "Photo album");
@define ("_lienketmxh", "MXH link");
@define ("_giolamviec", "Working hours");
@define ("_tieudelienhe", "Please fill out information to receive promotional information from us");
@define ("_chiduong", "Directions");
@define ("_goidien", "Call Phone");
@define ("_ketqua", "Result");
@define ("_timthay", "Found");
@define ("_timkiem", "Search");
@define ("_dongsanpham", "Product Line");
@define ("_nganhcongnghiep", "Industry and industry");
@define ("_chinhsachquydinh", "Policies & Regulations");
@define ("_theloai", "Category");
@define ("_dangkykhongthanhcong", "Registration failed, please try again");
@define ("_emaildaduocdangky", "Email is already registered!");
@define ("_dangkythanhcong", "Successful registration!");
@define ("_emailkhonghople", "Invalid email");
@define ("_banchuanhapemail", "You have not entered email");
@define ("_banchuanhaptukhoa", "You have not entered keywords");
@define ("_lamlai", "Redo");
@define ("_gui", "submit");
@define ("_noidung", "Content");
@define ("_tieude", "title");
@define ("_diachi", "Address");
@define ("_dienthoai", "Phone");
@define ("_sodienthoai", "Phone Number");
@define ("_hovaten", "Full name");
@define ("_baivietkhac", "Other Posts");
@define ("_xemchitiet", "View details");
@define ("_noidungchuacapnhat", "The content has not been updated yet. Please see other categories.");
@define ("_chitietsanpham", "Product details");
@define ("_giaban", "Sale Price");
@define ("_sanphamkhac", "Other Products");
@define ("_binhluan", "Comments");
@define ("_noidungchitiet", "Detailed content");
@define ("_gia", "Price");
@define ("_mota", "Description");
@define ("_masp", "Item Number");
@define ("_tongtruycap", "Total");
@define ("_thang", "Month");
@define ("_ngay", "Date");
@define ("_dangxem", "Viewing");
@define ("_dangonline", "Online");
@define ("_dangky", "Register");
@define ("_nhapemailcuaban", "Enter your email");
@define ("_ketnoivoichungtoi", "Connect with us");
@define ("_thongketruycap", "Access Statistics");
@define ("_vuilongdiendaydu", "Please fill in all required information and send it to us. We will respond as soon as possible.");
@define ("_moithongtindeubaomat", "All information is secure");
@define ("_guingay", "Send now");
@define ("_dangkynhantin", "Newsletter");
@define ("_thongtinlienhe", "Contact Information");
@define ("_videoclip", "Video - Clip");
@define ("_tintucsukien", "News - Events");
@define ("_sanphamnoibat", "Featured Products");
@define ("_dichvuchinh", "Main Services");
@define ("_danhmucsanpham", "Product Category");
@define ("_xemthem", "more");
@define ("_hotlinetuvan", "Hotline Consulting");
@define ("_thongtinlienheduocgui", "Contact has been successfully sent");
@define ("_hethongloi", "System error. Please try again!");
@define ("_lienhe", "Contact");
@define ("_tuyendung", "Recruiting");
@define ("_tintuc", "News");
@define ("_dichvu", "Services");
@define ("_sanpham", "Products");
@define ("_gioithieu", "About Us");
@define ("_trangchu", "Home");
@define ("_chatluong", "Quality");
@define ("_thitruong", "Market");
@define ("_dautu", "Investment");
@define ("_thongtin", "Information");
@define ("_giohang", "Shopping cart");
@define ("_thanhtoan", "Payment");
@define ("_clickvaodayneukhongmuondoilau", "Click here if you do not want to wait long");
@define ("_thongbao", "Notice");
@define ("_email", "Email");
@define ("_maxacnhankhongchinhxac", "Verification code is incorrect");
@define ("_themvaogiohang", "Add and cart");
@define ("_chuacosanpham", "No product");
@define ("_luotxem", "Views");
@define ("_sanphamduocthem", "This product has been added to your cart");
@define ("_tieptucmuahang", "Continue buying");
@define ("_xemgiohang", "View cart");
@define ("_hinhanh", "Image");
@define ("_ten", "Name");
@define ("_soluong", "Quantity");
@define ("_tong", "Total");
@define ("_thaotac", "Manipulation");
@define ("_muatiep", "Buy more");
@define ("_tonggia", "Total price");
@define ("_xoatatca", "Delete all");
@define ("_banmuonxoattatcagiohangkhong", "You want to delete all shopping carts");
@define ("_xoasanphamnay", "Delete this product");
@define ("_khongcosanphamnaotronggiohang", "There are no products in the shopping cart");
@define ("_chungtoinhanraspam", "We recognize that your spam !!");
@define ("_chinhsach", "Policy");
@define ("_dathangthanhcong", "Order successful");
@define ("_xinloiquykhach", "Sorry customers. <br> The system has failed, please try again");
@define ("_thuvien", "Library");
@define ("_taikhoan", "Account");
@define ("_dangxuat", "Log out");
@define ("_sanphamdachon", "Selected product");
@define ("_muangay", "Buy now");
@define ("_mangxahoi", "Social network");
@define ("_chinhsachhotro", "Support policy");
@define ("_thongtintaikhoan", "Account information");
@define ("_nhapemail", "Enter Email");
@define ("_tukhoatimkiem", "Search term");
@define ("_sanphambanchay", "Best seller");
@define ("_sanphammoi", "New product");
@define ("_dangnhap", "Login");
@define ("_tendangnhap", "Username");
@define ("_matkhau", "Password");
@define ("_dangnhap", "Login");
@define ("_nhomatkhau", "Remember password");
@define ("_quenmatkhau", "Forgot password");
@define ("_dangkytaikhoan", "Account registration");
@define ("_nhappassword", "Enter the password (Password is at least 6 characters)");
@define ("_nhappasswordcu", "Enter old password");
@define ("_nhappasswordmoi", "Enter a new password (Password is at least 6 characters)");
@define ("_nhaplaimatkhau", "Retype Password");
@define ("_nhaplaipasswordtren", "Retype the password above");
@define ("_nhaphoten", "Enter full name");
@define ("_nhapdiachi", "Enter address");
@define ("_nhapsodienthoai", "Enter phone number");
@define ("_nhaplai", "Re-enter");
@define ("_matkhauitnhat", "Password must be at least 6 characters");
@define ("_matkhaukhongtrungkhop", "Password does not match");
@define ("_xinhaynhapemail", "Please enter email");
@define ("_xinhaynhappassword", "Please enter the password");
@define ("_nhaplaimatkhaukhongchinhxac", "Retype password incorrect");
@define ("_xinhaynhaphoten", "Please enter your full name");
@define ("_xinhaynhapdiachi", "Please enter the address");
@define ("_sodienthoaikhongdung", "Invalid phone number");
@define ("_thongtintaikhoan", "Invalid phone number");
@define ("_kichhoattaikhoan", "Account activation");
@define ("_kichhoattaikhoanthanhcong", "Successfully activated account");
@define ("_clickvao", "Click");
@define ("_day", "here");
@define ("_detrovetrangchu", "to return to the home page");
@define ("_lichsumuahang", "Purchase history");
@define ("_banchuamuasanphamnaotrenwebsite", "You haven't bought anything on the website yet");
@define ("_donhangngay", "Daily order");
@define ("_madonhang", "Order code");
@define ("_trangthai", "Status");
@define ("_banquenmatkhau", "You Forgot Password");
@define ("_banhaynhapemailmabandadangky", "Please enter your registered email address here to receive a password via your email");
@define ("_laymatkhauthanhcong", "Successfully obtained a password. Your login information is!");
@define ("_laymatkhaukhongthanhcong", "Password failed to retrieve. Please retrieve password!");
@define ("_thongtingiaohang", "Shipping information");
@define ("_hinhthucthanhtoan", "Payments");
@define ("_ghichu", "Note");
@define ("_banhaydangnhapdecothevaoday", "Please login to be able to enter here");
@define ('_hangmoive', 'New arrival');
@define ('_banchay', 'Best sell');
@define ('_uudaihangtuan', 'Weekly deal');
@define ('_hoidap', 'FAQ');
@define ('_chamsockhachhang', 'Customer care');
@define ('_thanhtoanantoan', 'Secure payment');
@define ('_nhapdiachiemailcuaban', 'Enter you email address');
@define ('_quocgia', 'Country');
@define ('_chonquocgia', 'Choose a country');
@define ('_tinhthanh', 'Province / City');
@define ('_chontinhthanh', 'Select Province / City');
@define ('_quanhuyen', 'District');
@define ('_chonquanhuyen', 'Select District');
@define ('_xinhaychonquocgia', 'Please select a country');
@define ('_clickdexemhinhlonhon', 'Click to view larger image');
@define ('_sanphammuakem', 'Products purchased together');
@define ('_phivanchuyen', 'Shipping fee');
@define ('_tongthanhtoan', 'Total payment');
@define ('_thongtinhotro', 'Support information');
@define ('_tencongty', 'Company name');
@define ('_thongtindathangtuwebsite', 'Order information from website');
@define ('_dondathang', 'ORDER');
@define ('_bosuutap', 'Gallery');
@define ('_chao', 'Dear');
@define ('_camonbandadangkythanhvientren', 'Thank you for registering on this site');
@define ('_dekichhoattaikhoan', 'To activate member account, please click on the link below');
@define ('_tentruycap', 'Username');
@define ('_luuy', 'Note');
@define ('_daylathuhotrotudong', 'This is an automated support message, all responses to this mail are not approved');
@define ('_xacnhanmatkhau', 'Confirm Password');
@define ('_thongbaotu', 'Notice of Words');
@define ('_aidodadungemailnaydelaymatkhau', 'Someone used this email to get your membership password on the page');
@define ('_neudunglaban', 'If it is true that you want to retrieve the password please click the links below to retrieve your login information');
@define ('_nhanvaoday', 'Click Here');
@define ('_neubankhongyeucaulaylaipass', 'If you did not request a password, please ignore this email');
@define ('_banquenmatkhaunhapemaildelaylai', 'Forgot your password?. Please enter your registered email here to receive password via your email');
@define ('_guiemail', 'Send Email');
@define ('_laypassthanhcong', 'Successful password retrieval. Your login is!');
@define ('_laypasskhongthanhcong', 'Password failed to retrieve. Please retrieve the password!');
@define ('_dangkythanhvien', 'Registration');
@define ('_banphaikichhoat', 'Your account has not been activated. Please go to the registration email to activate!');
@define ('_dangnhapthanhcong', 'Login successful');
@define ('_tendangnhaphoacmatkhaukhongchinhxac', 'Incorrect username or password');
@define ('_bandadangkythanhcong', 'You have successfully registered. Please go to the registration email to activate your account');
@define ('_matkhaumoi', 'New password');
@define ('_nhaplaimatkhaumoi', 'Re-enter new password');
@define ('_capnhat', 'Update');
@define ('_banchuanhapmatkhaucu', 'You have not entered your old password');
@define ('_matkhauchuachinhxac', 'Incorrect password');
@define ('_capnhatthongtinthanhcong', 'Update information successful');
?>