"use client";
import { useCmsLocale } from "./cms-locale";

import { useEffect, useRef, useState } from "react";
import { Plus, X } from "lucide-react";
import { errorMessage } from "./cms-api";
import { type Category, type CatalogDefinition, catalogApi, categoryPath, slugify, uploadProductImage } from "./product-types";

export default function ProductCategories({ definition, categories, reload, editable }: { definition: CatalogDefinition; categories: Category[]; reload: () => Promise<void>; editable: boolean }) {
  const { t } = useCmsLocale();
  const request = <T,>(path: string, method = "GET", data?: unknown) => catalogApi<T>(definition, path, method, data);
  const [kind, setKind] = useState<Category["kind"]>(definition.category_depth > 0 ? "category" : definition.features.brand ? "brand" : "size");
  const [draft, setDraft] = useState<Category | null>(null);
  const [language, setLanguage] = useState<"vi" | "en">("vi");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { if (draft) dialog.current?.showModal(); }, [draft?.id]);
  const name = t(kind === "category" ? "danh mục" : kind === "brand" ? "hãng" : "kích thước");
  const items = categories.filter(category => category.kind === kind).sort((first, second) => categoryPath(first, categories).localeCompare(categoryPath(second, categories), "vi"));
  function change<K extends keyof Category>(key: K, value: Category[K]) { setDraft(current => current ? { ...current, [key]: value } : null); }
  function localized(key: "name" | "slug" | "description" | "seo_title" | "seo_description" | "seo_keywords") { return language === "vi" ? draft?.[key] || "" : draft?.translations?.en?.[key] || ""; }
  function changeLocalized(key: "name" | "slug" | "description" | "seo_title" | "seo_description" | "seo_keywords", value: string) {
    setDraft(current => current ? language === "vi" ? { ...current, [key]: value } : { ...current, translations: { ...current.translations, en: { ...current.translations?.en, [key]: value } } } : null);
  }
  function add() { setLanguage("vi"); setError(""); setDraft({ type: definition.key, id: 0, kind, parent_id: null, name: "", slug: "", image_id: null, image: null, description: "", seo_title: "", seo_description: "", seo_keywords: "", is_active: true, is_featured: false, sort_order: 0, translations: {} }); }
  return <section><div className="access-toolbar"><div className="access-tabs">{([["category", t("Danh mục ({0} cấp)", { "0": definition.category_depth })], ["brand", "Hãng"], ["size", "Kích thước"]] as const).filter(([key]) => key === "category" ? definition.category_depth > 0 : definition.features[key]).map(([key, label]) => <button className={`button ${kind === key ? "primary" : "secondary"}`} key={key} onClick={() => { setKind(key); setError(""); }}>{t(label)}</button>)}</div>{editable && <button className="button primary" onClick={add}><Plus size={16} />{t("Thêm")} {name}</button>}</div>{error && !draft && <p role="alert" className="cms-error">{t(error)}</p>}<div className="panel table-scroll"><table><thead><tr><th>{t("Tên / phân cấp")}</th><th>{t("Đường dẫn")}</th><th>{t("Thứ tự")}</th><th>{t("Hiển thị")}</th><th>{t("Thao tác")}</th></tr></thead><tbody>{items.map(category => <tr key={category.id}><td><strong>{categoryPath(category, categories)}</strong>{category.image && <img className="category-thumb" src={category.image.url} alt={category.name} />}</td><td>{category.slug}</td><td>{category.sort_order}</td><td><span className={`badge ${category.is_active ? "success" : "neutral"}`}>{category.is_active ? t("Hiển thị") : t("Ẩn")}</span></td><td>{editable ? <div className="album-actions"><button className="text-button" onClick={() => { setError(""); setLanguage("vi"); setDraft({ ...category }); }}>{t("Chỉnh sửa")}</button><button className="text-button" disabled={busy} onClick={async () => { if (!confirm(t("Xóa {0} “{1}”? Chỉ xóa được khi chưa được sử dụng.", { "0": name, "1": category.name }))) return; setBusy(true); setError(""); try { await request(`/cms/product-categories/${category.id}`, "DELETE"); await reload(); } catch (error) { setError(errorMessage(error)); } finally { setBusy(false); } }}>{t("Xóa")}</button></div> : t("Chỉ xem")}</td></tr>)}</tbody></table>{!items.length && <p className="access-empty">{t("Chưa có")} {name}. {editable && t("Bắt đầu bằng nút Thêm ở phía trên.")}</p>}</div>
    {draft && <dialog ref={dialog} className="cms-modal" aria-labelledby="category-dialog-title" onCancel={event => { event.preventDefault(); if (!busy) setDraft(null); }}><div className="cms-modal-body"><div className="panel-heading"><h2 id="category-dialog-title">{draft.id ? t("Chỉnh sửa") : t("Thêm")} {name}</h2><button className="icon-button" aria-label={t("Đóng")} disabled={busy} onClick={() => setDraft(null)}><X size={20} /></button></div><form className="cms-form" onSubmit={async event => { event.preventDefault(); if (!draft.name.trim()) { setLanguage("vi"); setError("Vui lòng nhập tên tiếng Việt."); return; } setBusy(true); setError(""); try { const { id, image, ...payload } = draft; void image; await request(id ? `/cms/product-categories/${id}` : "/cms/product-categories", id ? "PUT" : "POST", payload); setDraft(null); await reload(); } catch (error) { setError(errorMessage(error)); } finally { setBusy(false); } }}><fieldset className="product-fieldset cms-form" disabled={busy}><div className="product-tabs category-language-tabs" role="tablist" aria-label={t("Ngôn ngữ nhập liệu")}>
        {(["vi", "en"] as const).map(locale => <button type="button" role="tab" id={`category-language-${locale}`} aria-controls="category-language-panel" aria-selected={language === locale} tabIndex={language === locale ? 0 : -1} className={language === locale ? "active" : ""} key={locale} onClick={() => setLanguage(locale)} onKeyDown={event => {
          if (!["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) return;
          event.preventDefault();
          const next = event.key === "Home" ? "vi" : event.key === "End" ? "en" : locale === "vi" ? "en" : "vi";
          setLanguage(next);
          document.getElementById(`category-language-${next}`)?.focus();
        }}>{locale === "vi" ? t("Tiếng Việt") : "English"}</button>)}
      </div><div id="category-language-panel" role="tabpanel" aria-labelledby={`category-language-${language}`} className="category-localized-fields">
      <label>{t(language === "vi" ? "Tên tiếng Việt" : "Tên tiếng Anh")} {language === "vi" && "*"}<input autoFocus required={language === "vi"} value={localized("name")} maxLength={255} onChange={event => changeLocalized("name", event.target.value)} /></label>
      <label>Slug ({language.toUpperCase()})<div className="input-action"><input maxLength={255} value={localized("slug")} placeholder={t("Tự tạo từ tên nếu để trống")} onChange={event => changeLocalized("slug", event.target.value)} /><button type="button" className="button secondary" onClick={() => changeLocalized("slug", slugify(localized("name")))}>{t("Tạo từ tên")}</button></div></label><label>{t("Mô tả")} ({language.toUpperCase()})<textarea rows={3} value={localized("description")} maxLength={language === "vi" ? 10000 : 1000} onChange={event => changeLocalized("description", event.target.value)} /></label>
      <label>SEO title ({language.toUpperCase()})<input maxLength={255} value={localized("seo_title")} onChange={event => changeLocalized("seo_title", event.target.value)} /></label>
      <label>SEO description ({language.toUpperCase()})<textarea rows={3} maxLength={1000} value={localized("seo_description")} onChange={event => changeLocalized("seo_description", event.target.value)} /></label>
      <label>SEO keywords ({language.toUpperCase()})<input maxLength={500} value={localized("seo_keywords")} onChange={event => changeLocalized("seo_keywords", event.target.value)} /></label></div>
      <p className="subtle">{t("Phân cấp, ảnh và trạng thái dùng chung cho cả hai ngôn ngữ.")}</p>{kind === "category" && <label htmlFor="category-parent">{t("Danh mục cha")}<select id="category-parent" value={draft.parent_id || ""} onChange={event => change("parent_id", Number(event.target.value) || null)}><option value="">{t("Không có — danh mục cấp 1")}</option>{categories.filter(category => category.kind === "category" && category.id !== draft.id).map(category => <option value={category.id} key={category.id}>{categoryPath(category, categories)}</option>)}</select><small>{t("Tối đa {0} cấp; không thể chọn danh mục con làm cha.", { "0": definition.category_depth })}</small></label>}<label>{t("Ảnh danh mục")}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={async event => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; setBusy(true); setError(""); try { const media = await uploadProductImage(file, definition.module); change("image_id", media.id); change("image", media); } catch (error) { setError(error instanceof Error && !("status" in error) ? error.message : errorMessage(error)); } finally { setBusy(false); } }} /></label>{draft.image && <div className="album-actions"><img className="category-thumb" src={draft.image.url} alt={draft.name} /><button type="button" onClick={() => { change("image_id", null); change("image", null); }}>{t("Gỡ ảnh")}</button></div>}<label>{t("Thứ tự")}<input type="number" min="0" max="1000000" value={draft.sort_order} onChange={event => change("sort_order", Number(event.target.value))} /></label><label className="cms-checkbox"><input type="checkbox" checked={draft.is_active} onChange={event => change("is_active", event.target.checked)} />{t("Hiển thị")}</label><label className="cms-checkbox"><input type="checkbox" checked={draft.is_featured} onChange={event => change("is_featured", event.target.checked)} />{t("Nổi bật")}</label></fieldset>{error && <p role="alert" className="cms-error">{t(error)}</p>}<button className="button primary" disabled={busy}>{busy ? t("Đang xử lý…") : t("Lưu {0}", { "0": name })}</button></form></div></dialog>}
  </section>;
}
